application:
  subdomain: drizzle-gate
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://drizzle-gate:4983/
  background_task: true
  injects:
    - id: drizzle-gate-masterpass-autofill
      on: browser
      when:
        - /*
      do:
        - src: builtin://simple-inject-password
          params:
            password: "{{ .U.admin_password }}"
            requireUser: false
            allowPasswordOnly: true
services:
  drizzle-gate:
    # upstream: ghcr.io/drizzle-team/gateway:1.4.2
    image: registry.lazycat.cloud/czyt/drizzle-team/gateway:b5387383d1f9a523
    environment:
      - MASTERPASS={{ .U.admin_password }}
      - PORT=4983
      - STORE_PATH=/app
    binds:
      - /lzcapp/var/data:/app
